name: "CI/CD HAJ SERVER APP"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.1"

      - name: "Install dependencies and build"
        run: |
          npm install

      - name: "Deploy to remote server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/workers/haj_backend/
            git pull
            /usr/bin/npm install
            pm2 delete haj_backend
            PORT=3000 /usr/bin/pm2 start index.js --name "haj_backend"
